[project]
name = "simpletick"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "folium>=0.20.0",
    "ipykernel>=6.29.5",
    "pyais>=2.11.1",
    "pykx>=3.1.3",
]
